# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 340)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.fontEdit = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.fontEdit.setObjectName("fontEdit")
        self.gridLayout.addWidget(self.fontEdit, 4, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.ok = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 5, 0, 1, 3)
        self.countryButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.countryButton.setObjectName("countryButton")
        self.gridLayout.addWidget(self.countryButton, 2, 2, 1, 1)
        self.colorEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.colorEdit.setReadOnly(True)
        self.colorEdit.setObjectName("colorEdit")
        self.gridLayout.addWidget(self.colorEdit, 3, 1, 1, 1)
        self.country = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.country.setReadOnly(True)
        self.country.setObjectName("country")
        self.gridLayout.addWidget(self.country, 2, 1, 1, 1)
        self.font = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.font.setObjectName("font")
        self.gridLayout.addWidget(self.font, 4, 2, 1, 1)
        self.warn = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.warn.setText("")
        self.warn.setObjectName("warn")
        self.gridLayout.addWidget(self.warn, 7, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.surname = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 1, 1, 1, 2)
        self.name = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 2)
        self.colorButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.colorButton.setObjectName("colorButton")
        self.gridLayout.addWidget(self.colorButton, 3, 2, 1, 1)
        self.save = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 6, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Kolor:"))
        self.label_3.setText(_translate("Dialog", "Państwo:"))
        self.ok.setText(_translate("Dialog", "Ok"))
        self.countryButton.setText(_translate("Dialog", "Wybierz"))
        self.font.setText(_translate("Dialog", "Czcionka"))
        self.label.setText(_translate("Dialog", "Imie:"))
        self.label_2.setText(_translate("Dialog", "Nazwisko:"))
        self.colorButton.setText(_translate("Dialog", "Wybierz"))
        self.save.setText(_translate("Dialog", "Zapisz"))
